env:
  commonjs: true
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: 
  no-console: "off"
  no-unused-vars: 
    - 2
    - argsIgnorePattern: "^_"
