name: Terraform Plan and Add PR Comment
on:
  pull_request:
    branches:
      - deploy
permissions:
  contents: read
  id-token: write
jobs:
  terraform:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        id: configure-aws-credentials
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions
          aws-region: ${{ vars.AWS_REGION }}
          output-credentials: true
      - name: terraform init
        run: |
          # AWS認証情報を設定
          export AWS_ACCESS_KEY_ID=${{steps.configure-aws-credentials.outputs.aws-access-key-id}}
          export AWS_SECRET_ACCESS_KEY=${{steps.configure-aws-credentials.outputs.aws-secret-access-key}}
          export AWS_SESSION_TOKEN=${{steps.configure-aws-credentials.outputs.aws-session-token}}

          # Terraformの初期化
          terraform init -backend-config="region=${{ vars.AWS_REGION }}" -backend-config="bucket=throwtrash-tfstate-${{ vars.AWS_REGION }}"

          # TFVARファイルを作成
          echo "AppID=\"${{ secrets.APP_ID }}\"" >> terraform.tfvars
          echo "ApiUrl=\"${{ secrets.MECAB_API_URL }}\"" >> terraform.tfvars
          echo "ApiKey=\"${{ secrets.MECAB_API_KEY }}\"" >> terraform.tfvars
          echo "ReminderProductID=\"${{ secrets.REMINDER_PRODUCT_ID }}\"" >> terraform.tfvars
          echo "region=\"${{ vars.AWS_REGION }}\"" >> terraform.tfvars
      - name: terraform plan
        id: terraform-plan
        run: |
          # Terraform Plan
          terraform plan -var-file=terraform.tfvars -out=tfplan
      - name: Add PR Comment
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: ```${{ steps.terraform-plan.outputs.stdout }} ```
            });